-- ============================================================
-- Currency Converter Database Schema
-- Engine: InnoDB | Charset: utf8mb4
-- ============================================================


-- ------------------------------------------------------------
-- Table: currencies
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `currencies` (
  `id`          INT UNSIGNED    NOT NULL AUTO_INCREMENT,
  `code`        CHAR(3)         NOT NULL,
  `country_en`  VARCHAR(100)    NOT NULL DEFAULT '',
  `country_zh`  VARCHAR(100)    NOT NULL DEFAULT '',
  `currency_en` VARCHAR(100)    NOT NULL DEFAULT '',
  `currency_zh` VARCHAR(100)    NOT NULL DEFAULT '',
  `symbol`      VARCHAR(10)     NOT NULL DEFAULT '',
  `created_at`  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at`  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_code` (`code`),
  KEY `idx_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: rate_cache
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `rate_cache` (
  `id`              INT UNSIGNED    NOT NULL AUTO_INCREMENT,
  `base_currency`   CHAR(3)         NOT NULL,
  `target_currency` CHAR(3)         NOT NULL,
  `rate`            DECIMAL(20,8)   NOT NULL,
  `source`          VARCHAR(50)     NOT NULL DEFAULT 'unknown',
  `fetched_at`      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_currency_pair` (`base_currency`, `target_currency`),
  KEY `idx_base` (`base_currency`),
  KEY `idx_fetched` (`fetched_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: rate_history
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `rate_history` (
  `id`              INT UNSIGNED    NOT NULL AUTO_INCREMENT,
  `base_currency`   CHAR(3)         NOT NULL,
  `target_currency` CHAR(3)         NOT NULL,
  `rate`            DECIMAL(20,8)   NOT NULL,
  `rate_date`       DATE            NOT NULL,
  `created_at`      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_history` (`base_currency`, `target_currency`, `rate_date`),
  KEY `idx_pair_date` (`base_currency`, `target_currency`, `rate_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ------------------------------------------------------------
-- Table: api_rate_limit
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `api_rate_limit` (
  `id`            INT UNSIGNED    NOT NULL AUTO_INCREMENT,
  `ip_address`    VARCHAR(45)     NOT NULL,
  `endpoint`      VARCHAR(50)     NOT NULL,
  `request_count` INT UNSIGNED    NOT NULL DEFAULT 1,
  `window_start`  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ip_endpoint` (`ip_address`, `endpoint`),
  KEY `idx_window` (`window_start`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Seed Data: currencies
-- ============================================================
INSERT INTO `currencies` (`code`, `country_en`, `country_zh`, `currency_en`, `currency_zh`, `symbol`) VALUES
('AED', 'United Arab Emirates', '阿联酋',           'UAE Dirham',                 '阿联酋迪拉姆',       'د.إ'),
('AFN', 'Afghanistan',          '阿富汗',           'Afghan Afghani',              '阿富汗尼',           '؋'),
('ALL', 'Albania',              '阿尔巴尼亚',        'Albanian Lek',                '阿尔巴尼亚列克',     'L'),
('AMD', 'Armenia',              '亚美尼亚',          'Armenian Dram',               '亚美尼亚德拉姆',     '֏'),
('ANG', 'Netherlands Antilles', '荷属安的列斯',      'Netherlands Antillean Guilder','荷属安的列斯盾',    'ƒ'),
('AOA', 'Angola',               '安哥拉',            'Angolan Kwanza',              '安哥拉宽扎',         'Kz'),
('ARS', 'Argentina',            '阿根廷',            'Argentine Peso',              '阿根廷比索',         '$'),
('AUD', 'Australia',            '澳大利亚',          'Australian Dollar',           '澳元',               'A$'),
('AWG', 'Aruba',                '阿鲁巴',            'Aruban Florin',               '阿鲁巴弗罗林',       'ƒ'),
('AZN', 'Azerbaijan',           '阿塞拜疆',          'Azerbaijani Manat',           '阿塞拜疆马纳特',     '₼'),
('BAM', 'Bosnia and Herzegovina','波黑',             'Bosnian Convertible Mark',    '波黑可兑换马克',     'KM'),
('BBD', 'Barbados',             '巴巴多斯',          'Barbadian Dollar',            '巴巴多斯元',         'Bds$'),
('BDT', 'Bangladesh',           '孟加拉国',          'Bangladeshi Taka',            '孟加拉塔卡',         '৳'),
('BGN', 'Bulgaria',             '保加利亚',          'Bulgarian Lev',               '保加利亚列弗',       'лв'),
('BHD', 'Bahrain',              '巴林',              'Bahraini Dinar',              '巴林第纳尔',         'BD'),
('BIF', 'Burundi',              '布隆迪',            'Burundian Franc',             '布隆迪法郎',         'Fr'),
('BMD', 'Bermuda',              '百慕大',            'Bermudian Dollar',            '百慕大元',           '$'),
('BND', 'Brunei',               '文莱',              'Brunei Dollar',               '文莱元',             'B$'),
('BOB', 'Bolivia',              '玻利维亚',          'Bolivian Boliviano',          '玻利维亚诺',         'Bs'),
('BRL', 'Brazil',               '巴西',              'Brazilian Real',              '巴西雷亚尔',         'R$'),
('BSD', 'Bahamas',              '巴哈马',            'Bahamian Dollar',             '巴哈马元',           'B$'),
('BTN', 'Bhutan',               '不丹',              'Bhutanese Ngultrum',          '不丹努尔特鲁姆',     'Nu'),
('BWP', 'Botswana',             '博茨瓦纳',          'Botswana Pula',               '博茨瓦纳普拉',       'P'),
('BYN', 'Belarus',              '白俄罗斯',          'Belarusian Ruble',            '白俄罗斯卢布',       'Br'),
('BZD', 'Belize',               '伯利兹',            'Belize Dollar',               '伯利兹元',           'BZ$'),
('CAD', 'Canada',               '加拿大',            'Canadian Dollar',             '加元',               'C$'),
('CDF', 'DR Congo',             '刚果民主共和国',    'Congolese Franc',             '刚果法郎',           'Fr'),
('CHF', 'Switzerland',          '瑞士',              'Swiss Franc',                 '瑞士法郎',           'Fr'),
('CLP', 'Chile',                '智利',              'Chilean Peso',                '智利比索',           '$'),
('CNY', 'China',                '中国',              'Chinese Yuan',                '人民币',             '¥'),
('COP', 'Colombia',             '哥伦比亚',          'Colombian Peso',              '哥伦比亚比索',       '$'),
('CRC', 'Costa Rica',           '哥斯达黎加',        'Costa Rican Colón',           '科斯达黎加科朗',     '₡'),
('CUP', 'Cuba',                 '古巴',              'Cuban Peso',                  '古巴比索',           '$'),
('CVE', 'Cape Verde',           '佛得角',            'Cape Verdean Escudo',         '佛得角埃斯库多',     '$'),
('CZK', 'Czech Republic',       '捷克',              'Czech Koruna',                '捷克克朗',           'Kč'),
('DJF', 'Djibouti',             '吉布提',            'Djiboutian Franc',            '吉布提法郎',         'Fdj'),
('DKK', 'Denmark',              '丹麦',              'Danish Krone',                '丹麦克朗',           'kr'),
('DOP', 'Dominican Republic',   '多米尼加共和国',    'Dominican Peso',              '多米尼加比索',       'RD$'),
('DZD', 'Algeria',              '阿尔及利亚',        'Algerian Dinar',              '阿尔及利亚第纳尔',   'DA'),
('EGP', 'Egypt',                '埃及',              'Egyptian Pound',              '埃及镑',             'E£'),
('ERN', 'Eritrea',              '厄立特里亚',        'Eritrean Nakfa',              '厄立特里亚纳克法',   'Nfk'),
('ETB', 'Ethiopia',             '埃塞俄比亚',        'Ethiopian Birr',              '埃塞俄比亚比尔',     'Br'),
('EUR', 'Eurozone',             '欧元区',            'Euro',                        '欧元',               '€'),
('FJD', 'Fiji',                 '斐济',              'Fijian Dollar',               '斐济元',             'FJ$'),
('FKP', 'Falkland Islands',     '福克兰群岛',        'Falkland Islands Pound',      '福克兰群岛镑',       '£'),
('GBP', 'United Kingdom',       '英国',              'British Pound Sterling',      '英镑',               '£'),
('GEL', 'Georgia',              '格鲁吉亚',          'Georgian Lari',               '格鲁吉亚拉里',       '₾'),
('GHS', 'Ghana',                '加纳',              'Ghanaian Cedi',               '加纳塞地',           'GH₵'),
('GIP', 'Gibraltar',            '直布罗陀',          'Gibraltar Pound',             '直布罗陀镑',         '£'),
('GMD', 'Gambia',               '冈比亚',            'Gambian Dalasi',              '冈比亚达拉西',       'D'),
('GNF', 'Guinea',               '几内亚',            'Guinean Franc',               '几内亚法郎',         'Fr'),
('GTQ', 'Guatemala',            '危地马拉',          'Guatemalan Quetzal',          '危地马拉格查尔',     'Q'),
('GYD', 'Guyana',               '圭亚那',            'Guyanese Dollar',             '圭亚那元',           'G$'),
('HKD', 'Hong Kong',            '香港',              'Hong Kong Dollar',            '港元',               'HK$'),
('HNL', 'Honduras',             '洪都拉斯',          'Honduran Lempira',            '洪都拉斯伦皮拉',     'L'),
('HTG', 'Haiti',                '海地',              'Haitian Gourde',              '海地古德',           'G'),
('HUF', 'Hungary',              '匈牙利',            'Hungarian Forint',            '匈牙利福林',         'Ft'),
('IDR', 'Indonesia',            '印度尼西亚',        'Indonesian Rupiah',           '印尼盾',             'Rp'),
('ILS', 'Israel',               '以色列',            'Israeli New Shekel',          '以色列新谢克尔',     '₪'),
('INR', 'India',                '印度',              'Indian Rupee',                '印度卢比',           '₹'),
('IQD', 'Iraq',                 '伊拉克',            'Iraqi Dinar',                 '伊拉克第纳尔',       'ID'),
('IRR', 'Iran',                 '伊朗',              'Iranian Rial',                '伊朗里亚尔',         '﷼'),
('ISK', 'Iceland',              '冰岛',              'Icelandic Króna',             '冰岛克朗',           'kr'),
('JMD', 'Jamaica',              '牙买加',            'Jamaican Dollar',             '牙买加元',           'J$'),
('JOD', 'Jordan',               '约旦',              'Jordanian Dinar',             '约旦第纳尔',         'JD'),
('JPY', 'Japan',                '日本',              'Japanese Yen',                '日元',               '¥'),
('KES', 'Kenya',                '肯尼亚',            'Kenyan Shilling',             '肯尼亚先令',         'KSh'),
('KGS', 'Kyrgyzstan',           '吉尔吉斯斯坦',      'Kyrgystani Som',              '吉尔吉斯斯坦索姆',   'с'),
('KHR', 'Cambodia',             '柬埔寨',            'Cambodian Riel',              '柬埔寨瑞尔',         '៛'),
('KMF', 'Comoros',              '科摩罗',            'Comorian Franc',              '科摩罗法郎',         'CF'),
('KRW', 'South Korea',          '韩国',              'South Korean Won',            '韩元',               '₩'),
('KWD', 'Kuwait',               '科威特',            'Kuwaiti Dinar',               '科威特第纳尔',       'KD'),
('KYD', 'Cayman Islands',       '开曼群岛',          'Cayman Islands Dollar',       '开曼群岛元',         'CI$'),
('KZT', 'Kazakhstan',           '哈萨克斯坦',        'Kazakhstani Tenge',           '哈萨克斯坦坚戈',     '₸'),
('LAK', 'Laos',                 '老挝',              'Lao Kip',                     '老挝基普',           '₭'),
('LBP', 'Lebanon',              '黎巴嫩',            'Lebanese Pound',              '黎巴嫩镑',           'LL'),
('LKR', 'Sri Lanka',            '斯里兰卡',          'Sri Lankan Rupee',            '斯里兰卡卢比',       '₨'),
('LRD', 'Liberia',              '利比里亚',          'Liberian Dollar',             '利比里亚元',         'L$'),
('LSL', 'Lesotho',              '莱索托',            'Lesotho Loti',                '莱索托洛蒂',         'L'),
('LYD', 'Libya',                '利比亚',            'Libyan Dinar',                '利比亚第纳尔',       'LD'),
('MAD', 'Morocco',              '摩洛哥',            'Moroccan Dirham',             '摩洛哥迪拉姆',       'MAD'),
('MDL', 'Moldova',              '摩尔多瓦',          'Moldovan Leu',                '摩尔多瓦列伊',       'L'),
('MGA', 'Madagascar',           '马达加斯加',        'Malagasy Ariary',             '马达加斯加阿里亚里', 'Ar'),
('MKD', 'North Macedonia',      '北马其顿',          'Macedonian Denar',            '北马其顿第纳尔',     'ден'),
('MMK', 'Myanmar',              '缅甸',              'Myanmar Kyat',                '缅元',               'K'),
('MNT', 'Mongolia',             '蒙古',              'Mongolian Tögrög',            '蒙古图格里克',       '₮'),
('MOP', 'Macau',                '澳门',              'Macanese Pataca',             '澳门元',             'P'),
('MRU', 'Mauritania',           '毛里塔尼亚',        'Mauritanian Ouguiya',         '毛里塔尼亚乌吉亚',   'UM'),
('MUR', 'Mauritius',            '毛里求斯',          'Mauritian Rupee',             '毛里求斯卢比',       '₨'),
('MVR', 'Maldives',             '马尔代夫',          'Maldivian Rufiyaa',           '马尔代夫卢菲亚',     'Rf'),
('MWK', 'Malawi',               '马拉维',            'Malawian Kwacha',             '马拉维克瓦查',       'MK'),
('MXN', 'Mexico',               '墨西哥',            'Mexican Peso',                '墨西哥比索',         '$'),
('MYR', 'Malaysia',             '马来西亚',          'Malaysian Ringgit',           '马来西亚林吉特',     'RM'),
('MZN', 'Mozambique',           '莫桑比克',          'Mozambican Metical',          '莫桑比克梅蒂卡尔',   'MT'),
('NAD', 'Namibia',              '纳米比亚',          'Namibian Dollar',             '纳米比亚元',         'N$'),
('NGN', 'Nigeria',              '尼日利亚',          'Nigerian Naira',              '尼日利亚奈拉',       '₦'),
('NIO', 'Nicaragua',            '尼加拉瓜',          'Nicaraguan Córdoba',          '尼加拉瓜科多巴',     'C$'),
('NOK', 'Norway',               '挪威',              'Norwegian Krone',             '挪威克朗',           'kr'),
('NPR', 'Nepal',                '尼泊尔',            'Nepalese Rupee',              '尼泊尔卢比',         '₨'),
('NZD', 'New Zealand',          '新西兰',            'New Zealand Dollar',          '新西兰元',           'NZ$'),
('OMR', 'Oman',                 '阿曼',              'Omani Rial',                  '阿曼里亚尔',         'OMR'),
('PAB', 'Panama',               '巴拿马',            'Panamanian Balboa',           '巴拿马巴波亚',       'B/.'),
('PEN', 'Peru',                 '秘鲁',              'Peruvian Sol',                '秘鲁索尔',           'S/'),
('PGK', 'Papua New Guinea',     '巴布亚新几内亚',    'Papua New Guinean Kina',      '巴新基那',           'K'),
('PHP', 'Philippines',          '菲律宾',            'Philippine Peso',             '菲律宾比索',         '₱'),
('PKR', 'Pakistan',             '巴基斯坦',          'Pakistani Rupee',             '巴基斯坦卢比',       '₨'),
('PLN', 'Poland',               '波兰',              'Polish Złoty',                '波兰兹罗提',         'zł'),
('PYG', 'Paraguay',             '巴拉圭',            'Paraguayan Guaraní',          '巴拉圭瓜拉尼',       '₲'),
('QAR', 'Qatar',                '卡塔尔',            'Qatari Riyal',                '卡塔尔里亚尔',       'QR'),
('RON', 'Romania',              '罗马尼亚',          'Romanian Leu',                '罗马尼亚列伊',       'lei'),
('RSD', 'Serbia',               '塞尔维亚',          'Serbian Dinar',               '塞尔维亚第纳尔',     'din'),
('RUB', 'Russia',               '俄罗斯',            'Russian Ruble',               '俄罗斯卢布',         '₽'),
('RWF', 'Rwanda',               '卢旺达',            'Rwandan Franc',               '卢旺达法郎',         'RF'),
('SAR', 'Saudi Arabia',         '沙特阿拉伯',        'Saudi Riyal',                 '沙特里亚尔',         'SR'),
('SBD', 'Solomon Islands',      '所罗门群岛',        'Solomon Islands Dollar',      '所罗门群岛元',       'SI$'),
('SCR', 'Seychelles',           '塞舌尔',            'Seychellois Rupee',           '塞舌尔卢比',         '₨'),
('SDG', 'Sudan',                '苏丹',              'Sudanese Pound',              '苏丹镑',             'LS'),
('SEK', 'Sweden',               '瑞典',              'Swedish Krona',               '瑞典克朗',           'kr'),
('SGD', 'Singapore',            '新加坡',            'Singapore Dollar',            '新加坡元',           'S$'),
('SHP', 'Saint Helena',         '圣赫勒拿',          'Saint Helena Pound',          '圣赫勒拿镑',         '£'),
('SLE', 'Sierra Leone',         '塞拉利昂',          'Sierra Leonean Leone',        '塞拉利昂利昂',       'Le'),
('SOS', 'Somalia',              '索马里',            'Somali Shilling',             '索马里先令',         'Sh'),
('SRD', 'Suriname',             '苏里南',            'Surinamese Dollar',           '苏里南元',           '$'),
('SSP', 'South Sudan',          '南苏丹',            'South Sudanese Pound',        '南苏丹镑',           '£'),
('STN', 'São Tomé and Príncipe','圣多美和普林西比', 'São Tomé and Príncipe Dobra',  '多布拉',             'Db'),
('SYP', 'Syria',                '叙利亚',            'Syrian Pound',                '叙利亚镑',           '£'),
('SZL', 'Eswatini',             '斯威士兰',          'Swazi Lilangeni',             '斯威士兰里兰吉尼',   'L'),
('THB', 'Thailand',             '泰国',              'Thai Baht',                   '泰铢',               '฿'),
('TJS', 'Tajikistan',           '塔吉克斯坦',        'Tajikistani Somoni',          '塔吉克斯坦索莫尼',   'SM'),
('TMT', 'Turkmenistan',         '土库曼斯坦',        'Turkmenistani Manat',         '土库曼斯坦马纳特',   'T'),
('TND', 'Tunisia',              '突尼斯',            'Tunisian Dinar',              '突尼斯第纳尔',       'DT'),
('TOP', 'Tonga',                '汤加',              'Tongan Paʻanga',              '汤加潘阿格',         'T$'),
('TRY', 'Turkey',               '土耳其',            'Turkish Lira',                '土耳其里拉',         '₺'),
('TTD', 'Trinidad and Tobago',  '特立尼达和多巴哥',  'Trinidad and Tobago Dollar',  '特立尼达和多巴哥元', 'TT$'),
('TWD', 'Taiwan',               '台湾',              'New Taiwan Dollar',           '新台币',             'NT$'),
('TZS', 'Tanzania',             '坦桑尼亚',          'Tanzanian Shilling',          '坦桑尼亚先令',       'TSh'),
('UAH', 'Ukraine',              '乌克兰',            'Ukrainian Hryvnia',           '乌克兰格里夫纳',     '₴'),
('UGX', 'Uganda',               '乌干达',            'Ugandan Shilling',            '乌干达先令',         'USh'),
('USD', 'United States',        '美国',              'US Dollar',                   '美元',               '$'),
('UYU', 'Uruguay',              '乌拉圭',            'Uruguayan Peso',              '乌拉圭比索',         '$U'),
('UZS', 'Uzbekistan',           '乌兹别克斯坦',      'Uzbekistani Som',             '乌兹别克斯坦索姆',   'лв'),
('VES', 'Venezuela',            '委内瑞拉',          'Venezuelan Bolívar',          '委内瑞拉玻利瓦尔',   'Bs.S'),
('VND', 'Vietnam',              '越南',              'Vietnamese Dong',             '越南盾',             '₫'),
('VUV', 'Vanuatu',              '瓦努阿图',          'Vanuatu Vatu',                '瓦努阿图瓦图',       'Vt'),
('WST', 'Samoa',                '萨摩亚',            'Samoan Tālā',                 '萨摩亚塔拉',         'WS$'),
('XAF', 'Central Africa',       '中非',              'Central African CFA Franc',   '中非法郎',           'FCFA'),
('XCD', 'Eastern Caribbean',    '东加勒比',          'East Caribbean Dollar',       '东加勒比元',         'EC$'),
('XOF', 'West Africa',          '西非',              'West African CFA Franc',      '西非法郎',           'CFA'),
('XPF', 'French Polynesia',     '法属波利尼西亚',    'CFP Franc',                   '太平洋法郎',         'CFP'),
('YER', 'Yemen',                '也门',              'Yemeni Rial',                 '也门里亚尔',         '﷼'),
('ZAR', 'South Africa',         '南非',              'South African Rand',          '南非兰特',           'R'),
('ZMW', 'Zambia',               '赞比亚',            'Zambian Kwacha',              '赞比亚克瓦查',       'ZK'),
('ZWG', 'Zimbabwe',             '津巴布韦',          'Zimbabwe Gold',               '津巴布韦黄金',       'ZWG')
ON DUPLICATE KEY UPDATE
  country_en  = VALUES(country_en),
  country_zh  = VALUES(country_zh),
  currency_en = VALUES(currency_en),
  currency_zh = VALUES(currency_zh),
  symbol      = VALUES(symbol),
  updated_at  = CURRENT_TIMESTAMP;
